version: '2'
services:
  # Consul
  consul:
    image: gliderlabs/consul-server:latest
    command: "-server -bootstrap"
    ports:
      - 8500:8500
    networks:
      2immerse:
        aliases:
          - consul.service.consul


  registrator:
    image: gliderlabs/registrator:v7
    command: "consul://consul:8500"
    depends_on:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - 2immerse

  mqttbroker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    depends_on:
      - registrator
    labels:
      - "SERVICE_NAME=mqttbroker"
    networks:
      2immerse:
        aliases:
          - mqttbroker.service.consul

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - registrator
    labels:
      - "SERVICE_NAME=redis"
    networks:
      2immerse:
        aliases:
          - redis.service.consul

  wallclockservice:
    build: ./wallclock-service
    image: wallclockservice
    ports:
      - "6677:6677/udp"
      - "6676:6676"
      - "80"
    labels:
      - "SERVICE_NAME=wallclock-service"
    depends_on:
      - registrator
    networks:
      2immerse:
        aliases:
          - wallclock-service.service.consul

  sessioncontroller:
    build:
      context: ./src
      dockerfile: sessioncontroller/Dockerfile
    image: sessioncontroller
    ports:
      - "4000:4000"
    command: -c http://consul:8500 -l development
    volumes:
      - ./src/sessioncontroller/src:/usr/src/sessioncontroller/src
    depends_on:
      - registrator
      - mqttbroker
      - wallclockservice
    labels:
      - "SERVICE_NAME=sessioncontroller"
    environment:
        WALLCLOCK_SERVICE_WS_URL:  wss://wallclock-service.virt.ch.bbc.co.uk
    networks:
      2immerse:
        aliases:
          - sessioncontroller.service.consul
  
  synccontroller:
    build:
      context: ./src
      dockerfile: synccontroller/Dockerfile
    image: synccontroller
    ports:
      - "3002"
    command: -c http://consul:8500 -l development
    volumes:
      - ./src/synccontroller/src:/usr/src/synccontroller/src
    depends_on:
      - registrator
      - mqttbroker
      - wallclockservice
      - redis
    labels:
      - "SERVICE_NAME=synccontroller"
    environment:
        WALLCLOCK_SERVICE_WS_URL: wss://wallclock-service.virt.ch.bbc.co.uk
    networks:
      2immerse:
        aliases:
          - synccontroller.service.consul

  timelineobserver:
    build: src/timelineobserver/TimelineObserver/
    image: timelineobserver
    command: -r consul:8500 -d redis -b mqttbroker -t Sessions/+/timelines/+/state
    depends_on:
      - registrator
      - mqttbroker
      - redis
      - synccontroller
    labels:
      - "SERVICE_NAME=timelineobserver"
    environment:
        CONSUL_URL: localhost:8500
    networks:
      2immerse:
        aliases:
          - timelineobserver.service.consul

  synchronisedvideo:
      build: examples/synchronisedvideo
      image: synchronisedvideo
      volumes:
        - ./examples/synchronisedvideo/src:/usr/src/app/src
        - ./examples/synchronisedvideo/logs:/usr/src/app/logs
        - ./examples/synchronisedvideo/media:/usr/src/app/media
        - ./examples/synchronisedvideo/config:/usr/src/app/config
        - ./dist:/usr/src/app/dist
      ports:
        - 3000:3000
      depends_on:
        - sessioncontroller
      labels:
        - "SERVICE_NAME=synchronisedvideo"
      networks:
        2immerse:
          aliases:
            - synchronisedvideo.service.consul
  
networks:
  2immerse:
     driver: bridge

